---

#- name: Get vimfiles repo
#  git:
#    repo: "{{ vimfiles_repo }}"
#    dest: "{{ vimfiles_dir }}"
#  tags:
#    - vimfiles

#- name: Install vimfiles
#  command: "{{ vimfiles_install_cmd }}"
#  args:
#    chdir: "{{ vimfiles_dir }}"
#  tags:
#    - vimfiles

- name: symlink .vimrc
  file:
    src: "{{ home_dir }}/.vimrc"
    dest: "{{ home_dir }}/{{ vimfiles_dir }}/vimrc"
    state: link
  tags:
    - vimfiles
    - neovim
    - brew

- name: Install vim-vint pip package
  pip:
    name: vim-vint
    state: latest
  tags:
    - vimfiles
    - python
    - packages
