#!/usr/bin/env bash
#
# Sets up requirements to provision with ansible
#

#
# Clean display function
#
# usage:
#        display "My thing to output"
#
function display() {
    echo "----> $1"
}

# Install Xcode; on clean Mac call this script directly then use make to finish. 
if [ ! `which cc` ]; then
  display "Installing Xcode "
  sudo xcode-select --install 
fi

if [ ! `which pip` ]
then
    display "Installing pip"
    sudo easy_install pip
fi

#sudo pip install --upgrade -r requirements.txt
sudo pip install -r requirements.txt


if [ ! `which brew` ]
then
    display "Installing Homebrew"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# vim: ft=sh:
